-- MySQL Script generated by MySQL Workbench
-- Mon May 20 00:04:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema computo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema computo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `computo` DEFAULT CHARACTER SET utf8 ;
USE `computo` ;

-- -----------------------------------------------------
-- Table `computo`.`seiyu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`seiyu` (
  `idseiyu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `app` VARCHAR(45) NOT NULL,
  `apm` VARCHAR(45) NOT NULL,
  `cumpleaños` DATE NOT NULL,
  `sexo` INT NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`idseiyu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`personaje` (
  `idpersonaje` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `color_p` VARCHAR(45) NOT NULL,
  `color_o` VARCHAR(45) NOT NULL,
  `edad` INT NULL,
  `ocupacion` VARCHAR(45) NOT NULL,
  `idseiyu` INT NOT NULL,
  PRIMARY KEY (`idpersonaje`),
  INDEX `dobla_idx` (`idseiyu` ASC) VISIBLE,
  CONSTRAINT `dobla`
    FOREIGN KEY (`idseiyu`)
    REFERENCES `computo`.`seiyu` (`idseiyu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`animadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`animadora` (
  `idanimadora` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idanimadora`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cumpleaños` DATE NOT NULL,
  `sexo` INT NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`anime` (
  `idanime` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calif` INT NOT NULL,
  `sinopsis` LONGTEXT NOT NULL,
  `temporada` INT NOT NULL,
  `fecha_est` DATE NOT NULL,
  `idanimadora` INT NOT NULL,
  `idautor` INT NOT NULL,
  `episodios` INT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`idanime`, `nombre`),
  INDEX `idanimadora_idx` (`idanimadora` ASC) VISIBLE,
  INDEX `crea_idx` (`idautor` ASC) VISIBLE,
  CONSTRAINT `produce`
    FOREIGN KEY (`idanimadora`)
    REFERENCES `computo`.`animadora` (`idanimadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `crea`
    FOREIGN KEY (`idautor`)
    REFERENCES `computo`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`editorial` (
  `ideditorial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideditorial`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`manga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`manga` (
  `idmanga` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `calif` INT NOT NULL,
  `sinopsis` LONGTEXT NOT NULL,
  `fecha_est` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `tomos` INT NULL,
  `capitulos` INT NULL,
  `idautor` INT NOT NULL,
  `ideditorial` INT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`idmanga`, `nombre`),
  INDEX `crea_idx` (`idautor` ASC) VISIBLE,
  INDEX `publica_idx` (`ideditorial` ASC) VISIBLE,
  CONSTRAINT `crea`
    FOREIGN KEY (`idautor`)
    REFERENCES `computo`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `publica`
    FOREIGN KEY (`ideditorial`)
    REFERENCES `computo`.`editorial` (`ideditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`comentario` (
  `idcomentario` INT NOT NULL,
  `comentario` LONGTEXT NULL,
  `fecha` DATE NOT NULL,
  `idusuario` INT NOT NULL,
  `idanime` INT NOT NULL,
  `idmanga` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `publica_idx` (`idusuario` ASC) VISIBLE,
  INDEX `tiene_a_idx` (`idanime` ASC) VISIBLE,
  INDEX `tiene_m_idx` (`idmanga` ASC) VISIBLE,
  CONSTRAINT `publica`
    FOREIGN KEY (`idusuario`)
    REFERENCES `computo`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tiene_a`
    FOREIGN KEY (`idanime`)
    REFERENCES `computo`.`anime` (`idanime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tiene_m`
    FOREIGN KEY (`idmanga`)
    REFERENCES `computo`.`manga` (`idmanga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`evaluacion` (
  `idevaluacion` INT NOT NULL AUTO_INCREMENT,
  `eval` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `idusuario` INT NOT NULL,
  `idmanga` INT NOT NULL,
  `idanime` INT NOT NULL,
  PRIMARY KEY (`idevaluacion`),
  INDEX `evalua_idx` (`idusuario` ASC) VISIBLE,
  INDEX `evalua_m_idx` (`idmanga` ASC) VISIBLE,
  INDEX `evalua_a_idx` (`idanime` ASC) VISIBLE,
  CONSTRAINT `evalua`
    FOREIGN KEY (`idusuario`)
    REFERENCES `computo`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evalua_m`
    FOREIGN KEY (`idmanga`)
    REFERENCES `computo`.`manga` (`idmanga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evalua_a`
    FOREIGN KEY (`idanime`)
    REFERENCES `computo`.`anime` (`idanime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`ilustrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`ilustrador` (
  `idilustrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cumpleaños` DATE NOT NULL,
  `sexo` INT NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`idilustrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`ost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`ost` (
  `idost` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `artista` VARCHAR(45) NOT NULL,
  `idanime` INT NOT NULL,
  `anime_idanime` INT NOT NULL,
  `anime_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idost`, `nombre`, `anime_idanime`, `anime_nombre`),
  INDEX `tiene_idx` (`idanime` ASC) VISIBLE,
  INDEX `fk_ost_anime1_idx` (`anime_idanime` ASC, `anime_nombre` ASC) VISIBLE,
  CONSTRAINT `tiene`
    FOREIGN KEY (`idanime`)
    REFERENCES `computo`.`anime` (`idanime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ost_anime1`
    FOREIGN KEY (`anime_idanime` , `anime_nombre`)
    REFERENCES `computo`.`anime` (`idanime` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`dobla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`dobla` (
  `seiyu_idseiyu` INT NOT NULL,
  `personaje_idpersonaje` INT NOT NULL,
  `numero` INT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`seiyu_idseiyu`, `personaje_idpersonaje`),
  INDEX `fk_seiyu_has_personaje_personaje1_idx` (`personaje_idpersonaje` ASC) VISIBLE,
  INDEX `fk_seiyu_has_personaje_seiyu1_idx` (`seiyu_idseiyu` ASC) VISIBLE,
  CONSTRAINT `fk_seiyu_has_personaje_seiyu1`
    FOREIGN KEY (`seiyu_idseiyu`)
    REFERENCES `computo`.`seiyu` (`idseiyu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seiyu_has_personaje_personaje1`
    FOREIGN KEY (`personaje_idpersonaje`)
    REFERENCES `computo`.`personaje` (`idpersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`aparece_en_a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`aparece_en_a` (
  `anime_idanime` INT NOT NULL,
  `personaje_idpersonaje` INT NOT NULL,
  `primera_ap` DATE NOT NULL,
  PRIMARY KEY (`anime_idanime`, `personaje_idpersonaje`),
  INDEX `fk_anime_has_personaje_personaje1_idx` (`personaje_idpersonaje` ASC) VISIBLE,
  INDEX `fk_anime_has_personaje_anime1_idx` (`anime_idanime` ASC) VISIBLE,
  CONSTRAINT `fk_anime_has_personaje_anime1`
    FOREIGN KEY (`anime_idanime`)
    REFERENCES `computo`.`anime` (`idanime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_has_personaje_personaje1`
    FOREIGN KEY (`personaje_idpersonaje`)
    REFERENCES `computo`.`personaje` (`idpersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`a_es`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`a_es` (
  `anime_idanime` INT NOT NULL,
  `anime_nombre` VARCHAR(45) NOT NULL,
  `genero_idgenero` INT NOT NULL,
  `genero_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`anime_idanime`, `anime_nombre`, `genero_idgenero`, `genero_nombre`),
  INDEX `fk_anime_has_genero_genero1_idx` (`genero_idgenero` ASC, `genero_nombre` ASC) VISIBLE,
  INDEX `fk_anime_has_genero_anime1_idx` (`anime_idanime` ASC, `anime_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_anime_has_genero_anime1`
    FOREIGN KEY (`anime_idanime` , `anime_nombre`)
    REFERENCES `computo`.`anime` (`idanime` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_has_genero_genero1`
    FOREIGN KEY (`genero_idgenero` , `genero_nombre`)
    REFERENCES `computo`.`genero` (`idgenero` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`ve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`ve` (
  `anime_idanime` INT NOT NULL,
  `anime_nombre` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_nombre` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cal` INT NULL,
  `episodio` INT NOT NULL,
  PRIMARY KEY (`anime_idanime`, `anime_nombre`, `usuario_idusuario`, `usuario_nombre`),
  INDEX `fk_anime_has_usuario_usuario1_idx` (`usuario_idusuario` ASC, `usuario_nombre` ASC) VISIBLE,
  INDEX `fk_anime_has_usuario_anime1_idx` (`anime_idanime` ASC, `anime_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_anime_has_usuario_anime1`
    FOREIGN KEY (`anime_idanime` , `anime_nombre`)
    REFERENCES `computo`.`anime` (`idanime` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_nombre`)
    REFERENCES `computo`.`usuario` (`idusuario` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`lee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`lee` (
  `usuario_idusuario` INT NOT NULL,
  `usuario_nombre` VARCHAR(30) NOT NULL,
  `manga_idmanga` INT NOT NULL,
  `manga_nombre` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `capitulo` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `usuario_nombre`, `manga_idmanga`, `manga_nombre`),
  INDEX `fk_usuario_has_manga_manga1_idx` (`manga_idmanga` ASC, `manga_nombre` ASC) VISIBLE,
  INDEX `fk_usuario_has_manga_usuario1_idx` (`usuario_idusuario` ASC, `usuario_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_manga_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_nombre`)
    REFERENCES `computo`.`usuario` (`idusuario` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_manga_manga1`
    FOREIGN KEY (`manga_idmanga` , `manga_nombre`)
    REFERENCES `computo`.`manga` (`idmanga` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`dibuja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`dibuja` (
  `manga_idmanga` INT NOT NULL,
  `manga_nombre` VARCHAR(100) NOT NULL,
  `ilustrador_idilustrador` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`manga_idmanga`, `manga_nombre`, `ilustrador_idilustrador`),
  INDEX `fk_manga_has_ilustrador_ilustrador1_idx` (`ilustrador_idilustrador` ASC) VISIBLE,
  INDEX `fk_manga_has_ilustrador_manga1_idx` (`manga_idmanga` ASC, `manga_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_manga_has_ilustrador_manga1`
    FOREIGN KEY (`manga_idmanga` , `manga_nombre`)
    REFERENCES `computo`.`manga` (`idmanga` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manga_has_ilustrador_ilustrador1`
    FOREIGN KEY (`ilustrador_idilustrador`)
    REFERENCES `computo`.`ilustrador` (`idilustrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`m_es`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`m_es` (
  `genero_idgenero` INT NOT NULL,
  `genero_nombre` VARCHAR(45) NOT NULL,
  `manga_idmanga` INT NOT NULL,
  `manga_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`genero_idgenero`, `genero_nombre`, `manga_idmanga`, `manga_nombre`),
  INDEX `fk_genero_has_manga_manga1_idx` (`manga_idmanga` ASC, `manga_nombre` ASC) VISIBLE,
  INDEX `fk_genero_has_manga_genero1_idx` (`genero_idgenero` ASC, `genero_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_manga_genero1`
    FOREIGN KEY (`genero_idgenero` , `genero_nombre`)
    REFERENCES `computo`.`genero` (`idgenero` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_has_manga_manga1`
    FOREIGN KEY (`manga_idmanga` , `manga_nombre`)
    REFERENCES `computo`.`manga` (`idmanga` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `computo`.`aparece_en_m`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `computo`.`aparece_en_m` (
  `personaje_idpersonaje` INT NOT NULL,
  `manga_idmanga` INT NOT NULL,
  `manga_nombre` VARCHAR(100) NOT NULL,
  `primera_ap` DATE NOT NULL,
  PRIMARY KEY (`personaje_idpersonaje`, `manga_idmanga`, `manga_nombre`),
  INDEX `fk_personaje_has_manga_manga1_idx` (`manga_idmanga` ASC, `manga_nombre` ASC) VISIBLE,
  INDEX `fk_personaje_has_manga_personaje1_idx` (`personaje_idpersonaje` ASC) VISIBLE,
  CONSTRAINT `fk_personaje_has_manga_personaje1`
    FOREIGN KEY (`personaje_idpersonaje`)
    REFERENCES `computo`.`personaje` (`idpersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaje_has_manga_manga1`
    FOREIGN KEY (`manga_idmanga` , `manga_nombre`)
    REFERENCES `computo`.`manga` (`idmanga` , `nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
